### ISSUE TITLE
asdf reshim qt seems to be missing qmake

### ISSUE THREAD

**Issue by nigelatdas** [jamesstidard/asdf-qt#2]
I'm trying to get qmake in my path. 

For some reason asdf is not making a shim for it. 

any ideas?

**Comment by nigelatdas** [comment]
Found it. 

qmake is not marked as executable in the install folder.

**Comment by jamesstidard** [comment]
Hi @nigelatdas thats interesting. What version of qt had you installed?

**Comment by nigelatdas** [comment]
5.13.2

**Comment by jamesstidard** [comment]
Got around to adding a line to assure `qmake` is executable after install. Thanks for reporting and troubleshooting this.
